org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

project_type=LIBRARY

lib.group=at.minecraftschurli.mods
lib.name=easydatagenlib
lib.version=2.1
lib.vendor=MinecraftschurliMods

java_version=25

github.owner=MinecraftschurliMods
github.repo=easydatagenlib

license.name=MIT
license.url=https://opensource.org/licenses/MIT
license.file=LICENSE

mc_version=26.1-pre-2
neo_version=26.1.0.0-alpha.0+pre-2.20260313.154450
