@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.minecraftschurlimods.easydatagenlib.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
