@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.minecraftschurlimods.easydatagenlib.api;

import com.mojang.blaze3d.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;