@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.minecraftschurlimods.easydatagenlib.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
