name: 'Build Commit'
on:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.[0-9]+'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        id: build
        env:
          MAVEN_URL: ${{ vars.MAVEN_URL }}
          MAVEN_USER: ${{ vars.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          RELEASE_TYPE: snapshot
        with:
          arguments: -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME build publish
